"""Slash commands shared by external managers and the Symphony TUI catalog."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from coding_agent.config import ensure_spawn_settings, symphony_dir
from coding_agent.personalities import load_personalities
from coding_agent.persistence.jsonl import JsonlPersistence
from coding_agent.persistence.artifacts import publish, safe_path
from coding_agent.tui.commands.catalog import EFFORTS, SLASH_COMMANDS


def catalog() -> list[dict[str, str]]:
    return [
        {"name": item.name, "description": item.description, "inputHint": item.argument}
        for item in SLASH_COMMANDS
    ]


def _state_path(session_id: str) -> Path:
    # The session id is generated by Symphony, but avoid treating it as a path.
    import uuid

    return symphony_dir() / "protocols" / f"{uuid.UUID(session_id)}.json"


def _agent_state_path(agent: Any) -> Path:
    persistence = getattr(agent, "persistence", None)
    if not isinstance(persistence, JsonlPersistence):
        return _state_path(agent.session_id)

    path = safe_path(persistence.session_dir(agent.session_id), "state.json")
    if not path.exists():
        try:
            legacy = _state_path(agent.session_id)
        except ValueError:
            # JSONL sessions also support non-UUID identifiers.
            return path
        if legacy.is_file():
            path.parent.mkdir(parents=True, exist_ok=True)
            publish(path, legacy.read_bytes())
            legacy.unlink()
    return path


def load_state(agent: Any) -> None:
    try:
        path = _agent_state_path(agent)
    except ValueError:
        return
    if not path.exists():
        return
    data = json.loads(path.read_text(encoding="utf-8"))
    mode = data.get("mode", "build")
    if mode in {"build", "plan"}:
        agent.set_mode(mode)
    effort = data.get("effort")
    if effort in EFFORTS:
        agent.harness.reasoning_effort = None if effort == "default" else effort


def _save_state(agent: Any, **changes: str) -> None:
    path = _agent_state_path(agent)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}
    data.update(changes)
    publish(path, (json.dumps(data, indent=2) + "\n").encode("utf-8"))


def _git_diff(workspace: Path) -> str:
    result = subprocess.run(
        ["git", "diff", "--stat", "HEAD"], cwd=workspace, capture_output=True,
        text=True, timeout=10, check=False,
    )
    return result.stdout.strip() or result.stderr.strip() or "No changes in tracked files."


async def execute(agent: Any, value: str) -> str:
    """Execute a command without sending it to a model."""
    command, _, argument = value[1:].partition(" ")
    command, argument = command.lower(), argument.strip()
    if command in {"help"}:
        return "\n".join(f"{item.usage} — {item.description}" for item in SLASH_COMMANDS)
    if command == "status":
        return (
            f"Model: {agent.harness.model_id}\nSession: {agent.session_id}\n"
            f"Mode: {agent.mode}\nPersonality: {agent.config.personality}\n"
            f"Effort: {agent.harness.reasoning_effort or 'default'}"
        )
    if command == "session":
        from coding_agent.persistence.presentation import session_report

        return await session_report(agent)
    if command == "context":
        report = await agent.context_report()
        return str(report)
    if command == "compact":
        before, after = await agent.compact_conversation()
        return f"Compacted conversation: {before} → {after} messages."
    if command in {"mode", "plan"}:
        mode = "plan" if command == "plan" else argument.lower()
        if not mode:
            return f"Current mode: {agent.mode}. Options: build, plan."
        if mode not in {"build", "plan"}:
            return "Choose /mode build or /mode plan."
        agent.set_mode(mode)
        _save_state(agent, mode=mode)
        return f"Switched to {agent.mode} mode."
    if command == "effort":
        if not argument:
            return f"Current effort: {agent.harness.reasoning_effort or 'default'}. Options: {', '.join(EFFORTS)}."
        if argument.lower() not in EFFORTS:
            return f"Unknown effort. Options: {', '.join(EFFORTS)}."
        agent.harness.reasoning_effort = None if argument == "default" else argument.lower()
        _save_state(agent, effort=argument.lower())
        return f"Reasoning effort: {argument.lower()}."
    if command == "personality":
        choices = {item.id: item for item in load_personalities()}
        if not argument:
            return f"Current: {agent.config.personality}. Options: {', '.join(choices)}."
        if argument not in choices:
            return f"Unknown personality: {argument}. Options: {', '.join(choices)}."
        agent.config = ensure_spawn_settings(agent.workspace, overrides={"personality": argument})
        agent.apply_system_prompt()
        return f"Personality: {choices[argument].name}."
    if command == "jev":
        value = argument.lower()
        if not argument or value == "toggle":
            enabled = not agent.config.evaluation.enabled
        else:
            enabled = value not in {"off", "false", "disable", "0"}
        settings: dict[str, Any] = {"enabled": enabled}
        if argument and value not in {"on", "enable", "true", "1", "off", "false", "disable", "0"}:
            settings["rule"] = argument
        agent.config = ensure_spawn_settings(agent.workspace, overrides={"evaluation": settings})
        agent.apply_system_prompt()
        return f"Jev {'enabled' if enabled else 'disabled'} for the next turn."
    if command == "model":
        models = [item.full_id for item in agent.registry.models() if item.provider in agent.registry.namespaces()]
        if argument:
            return "Select the model in Zeron's model picker; it controls the model for this chat."
        return f"Current model: {agent.harness.model_id}\nAvailable: {', '.join(models)}"
    if command == "plans":
        if argument:
            path = agent.plan_store.select(argument)
            return path.read_text(encoding="utf-8") if path else f"Unknown plan: {argument}."
        paths = agent.plan_store.list_paths()
        return "\n".join(str(path.relative_to(agent.workspace)) for path in paths) or "No saved plans."
    if command == "learning":
        from coding_agent.learning.store import LearningStore

        store = getattr(agent, "learning_store", None)
        if store is None:
            # Lightweight protocol hosts/tests may not expose the agent's store.
            store = LearningStore(agent.workspace)
        return store.to_markdown()
    if command == "installed":
        skills = [item.name for item in agent.skill_registry.skills]
        plugins = [str(getattr(item, "name", item)) for item in agent.loaded_plugins]
        return f"Skills: {', '.join(skills) or 'none'}\nPlugins: {', '.join(plugins) or 'none'}"
    if command == "diff":
        return _git_diff(agent.workspace)
    if command == "dashboard":
        root = symphony_dir() / "active"
        entries = sorted(root.iterdir()) if root.exists() else []
        return "\n".join(path.name for path in entries) or "No active agents."
    if command == "reload":
        return "Symphony reloads its configuration each time Zeron starts a turn."
    if command == "provider":
        return "Configure a provider with its API key in Symphony's environment, then use /model."
    if command == "langfuse":
        return "Configure Langfuse credentials in ~/.symphony/.env; Symphony loads them on the next turn."
    if command == "new":
        return "Use Zeron's /zeron:new to open a fresh conversation."
    if command == "clear":
        return "Use Zeron's conversation controls to clear the visible transcript."
    if command == "quit":
        return "Close the Zeron window to exit."
    raise ValueError(f"Unknown command: /{command}. Type /help to see commands.")
