# Generated by scripts/generate_models.py. Do not edit by hand.

from core_ai.models.types import ModelInfo

OPENAI_MODELS = (
    ModelInfo(id="gpt-4.1", provider="openai", api="responses"),
    ModelInfo(id="gpt-4.1-mini", provider="openai", api="responses"),
    ModelInfo(id="gpt-4o-mini", provider="openai", api="responses"),
    ModelInfo(id="gpt-5.6-luna", provider="openai", api="responses"),
    ModelInfo(id="o3", provider="openai", api="chat_completions"),
)

ANTHROPIC_MODELS = (
    ModelInfo(id="claude-fable-5", provider="anthropic", api="messages"),
    ModelInfo(id="claude-haiku-4-5", provider="anthropic", api="messages"),
    ModelInfo(id="claude-opus-5", provider="anthropic", api="messages"),
    ModelInfo(id="claude-sonnet-5", provider="anthropic", api="messages"),
)

GEMINI_MODELS = (
    ModelInfo(id="gemini-3.1-pro-preview", provider="gemini", api="generate_content"),
    ModelInfo(id="gemini-3.5-flash", provider="gemini", api="generate_content"),
    ModelInfo(id="gemini-3.6-flash", provider="gemini", api="generate_content"),
    ModelInfo(id="gemini-3.7-flash", provider="gemini", api="generate_content"),
)

ALL_MODELS = OPENAI_MODELS + ANTHROPIC_MODELS + GEMINI_MODELS
