# Generated by scripts/generate_openai_models.py. Do not edit by hand.

from core_ai.models.types import ModelInfo

OPENAI_MODELS = (
    ModelInfo(id="gpt-5.6-luna", provider="openai", api="responses"),
    ModelInfo(id="o3", provider="openai", api="chat_completions"),
)
