#!/usr/bin/env python3
from __future__ import annotations

import os
from pathlib import Path

import httpx

OUTPUT = Path(__file__).resolve().parents[1] / "src/core_ai/models/generated.py"
SUPPORTED_PREFIXES = ("gpt-", "o1", "o3", "o4")
CHAT_COMPLETIONS_PREFIXES = ("o1", "o3", "o4")


def model_api(model_id: str) -> str:
    if model_id.startswith(CHAT_COMPLETIONS_PREFIXES):
        return "chat_completions"
    return "responses"


def fetch_models(api_key: str, base_url: str) -> list[str]:
    response = httpx.get(
        f"{base_url.rstrip('/')}/models",
        headers={"Authorization": f"Bearer {api_key}"},
        timeout=30.0,
    )
    response.raise_for_status()
    data = response.json().get("data", [])
    return sorted(
        model["id"]
        for model in data
        if isinstance(model, dict)
        and isinstance(model.get("id"), str)
        and model["id"].startswith(SUPPORTED_PREFIXES)
    )


def render(models: list[str]) -> str:
    lines = [
        "# Generated by scripts/generate_openai_models.py. Do not edit by hand.",
        "",
        "from core_ai.models.types import ModelInfo",
        "",
        "OPENAI_MODELS = (",
    ]
    lines.extend(
        f'    ModelInfo(id="{model_id}", provider="openai", api="{model_api(model_id)}"),'
        for model_id in models
    )
    lines.extend((")", ""))
    return "\n".join(lines)


def main() -> None:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise SystemExit("OPENAI_API_KEY is required")
    base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1")
    models = fetch_models(api_key, base_url)
    OUTPUT.write_text(render(models))
    print(f"wrote {len(models)} OpenAI models to {OUTPUT}")


if __name__ == "__main__":
    main()
